### ISSUE TITLE
[Quilt] 3-way incompatibility causing a crash

### ISSUE THREAD

**Issue by SplendidAlakey** [ArtixAllMighty/FatChickens#4]
**MC** 1.19.2
**QSL** 4.0.0-beta13
**FatChickens** 2.0.2
**[Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)** 2.2.3
**[Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric)** 3.4.0

To reproduce install all 3 mods and its requirements, then launch the game. It will crash on startup. Removing either one of these mods lets the game start.

Fabric does not have the same issue with this set of mods. Let me know if this needs to be reported to somewhere else, but FatChickens appears a lot in the log, so reporting here first.

Logs: https://gist.github.com/Footage2-Amply-Pounce/7dfb98d010d337420d2db72e88f292e2

P.S. Sorry, tried to report it before the 2.0.2 version went up, took me a while to narrow down the set of mods needed to reproduce the crash.

**Comment by AbsolemJackdaw** [comment]
.3 should fix this. please report if it didnt ! 
https://www.curseforge.com/minecraft/mc-mods/fat-chicken/files/4014443

**Comment by SplendidAlakey** [comment]
I cant reopen the issue, but, unfortunately, the crash still happens. Same conditions, but the logs are a bit different: https://gist.github.com/Footage2-Amply-Pounce/7dfb98d010d337420d2db72e88f292e2 (same link, but I updated the logs).

**Comment by AbsolemJackdaw** [comment]
i was about to say how there already was a fix for that but looks like it got stuck in the upload process yesterday evening when I uploaded it and went to bed ...

this should be the last fix i promise :D
